### ISSUE TITLE
[Bug]: Tag quest in FTB Quest mutiplayer do not load items or name right

### ISSUE THREAD

**Issue by Joshernoob** [FTBTeam/FTB-Mods-Issues#1289]
### Mod

FTB Quest

### Mod version

2001.4.8

### Forge / Fabric version

Forge 1.20.1

### Modpack & version

Cave's Depths - Self Made Pack

### What issue are you having?

![Screenshot 2024-07-25 203413](https://github.com/user-attachments/assets/9aae2d29-5a26-49c7-b79c-a0b96c3af402)
As the Image shows All Tagged Quests show three lines on server, tested in single player and they work fine, 

HAve the required mod to make tags work and confimred it when i tested single player

### Crashlogs

N/A

### Steps to reproduce

Load the pack
Join server - I have one if needed
Quest will be errored
Try single player, they work and look just fine

### Anything else to note?

The quest still funtion just seem to be a visual bug of some kind

**Comment by desht** [comment]
I need a better explanation of the issue.  What do you mean by "All Tagged Quests"?

**Comment by Joshernoob** [comment]
> 

any quest using a item tags instead of an item id

i have the mods needed to use tags instead of ids but there not showing right here

**Comment by Joshernoob** [comment]
sorry let me re-state that as i was exosted and typed it out quick.

Any quest that i used a tag in Example: "tag:stone" would turn into the lines you see there icons breaking as well as the names of the quests.

Any quest that i use item id like "minecraft:stone" they would be fine the icons and names not breaking

This only seems to happen when I join the packs server and not single player and only seem to effect the icons and names themself meaning the quest still work but you can't see what your going after.

Example: the lines top of the crafting table meant to be a pickaxe quest with "forge:pickaxe" as the tag yet it won't grab any of the images of the pickaxes that are in the "forge:pickaxe" list and the name just blank

I have the required mods to get Tags for quest to work 
-FTB Quests 
- FTB XMods Combat
- Item Filters

I also only have theses mods that target the quest book
- Text animation
- FTB Teams
- FTB Quest Optimizer
- Recourse Pack, Custom to the modpack

**Comment by desht** [comment]
OK, I have seen this issue before, but I'd believed it was fixed in 2001.4.7 - see #1253 (user there confirmed the problem was resolved).

Are you definitely on 2001.4.8?

**Comment by Joshernoob** [comment]
![Screenshot 2024-07-29 153628](https://github.com/user-attachments/assets/100bada9-9e90-49b2-8bfe-210f20f4e197)
can confirm as the picture shows that I'm on 2001.4.8

**Comment by Joshernoob** [comment]
Sorry it took so long but seem an update to one of the addon mods fixed this as I updated my server resently and it is no longer broken
my guess is the update to FTB Quest Optimizer fixed it

**Comment by alarmgoose** [comment]
> Sorry it took so long but seem an update to one of the addon mods fixed this as I updated my server resently and it is no longer broken my guess is the update to FTB Quest Optimizer fixed it

I'm running into this same problem at this moment. I installed Quest Optimizer but it didn't fix it. Do you have any other suggestions ?

**Comment by Joshernoob** [comment]
> > Sorry it took so long but seem an update to one of the addon mods fixed this as I updated my server resently and it is no longer broken my guess is the update to FTB Quest Optimizer fixed it
> 
> I'm running into this same problem at this moment. I installed Quest Optimizer but it didn't fix it. Do you have any other suggestions ?

I'd try the list of addon's I listed and see if adding them fixes it 

Also do remember that these are required 
- FTB XMods Combat
- Item Filters/ FTB Filters

These are the extra addon's I used before I fixed
- Text animation
- FTB Teams
- FTB Quest Optimizer
- can't give the data pack but you can try your own.

Just go threw and add/remove them until it works. If none do then it may be a server thing with resetting files or luck until it's confirmed fixed in main mod.
