### ISSUE TITLE
[Bug]: Ftb Quests not detecting items in inventory

### ISSUE THREAD

**Issue by Abalieno** [FTBTeam/FTB-Mods-Issues#650]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.6-build.176

### Forge / Fabric version

1.19.2 0.14.13 fabric

### Modpack & version

Gregorian Nightmares, my own

### What issue are you having?

For some absurd reason, ftb quests isn't detecting... a vanilla minecraft:stick

I've tried repeatedly dropping it and getting it back, crafting it again, even pulling it from REI in cheat mode. The quest won't progress in any way.

Then I quit and reload, and by the time I logged back in the quest was completed... Only to get stuck again 3 quests later with a completely different item. Once again sitting in the inventory, but the quest just won't complete.

![ykiul](https://user-images.githubusercontent.com/4656436/214349625-8ed05197-351a-48ab-8457-c1a9f281c0e9.png)

![yukkiil](https://user-images.githubusercontent.com/4656436/214349699-4a6f6f9a-fe5e-41c6-ac7a-1615b7adf141.png)

### Steps to reproduce

Not simple to reproduce since it seems to do it on different items.

But it just stops detecting simple items and not being able to complete quests. I need some hints to even START troubleshooting this. I can't find any explanation.

**Comment by desht** [comment]
I too can't find any explanation (or indeed reproduce the problem - every item task I've tried creating works fine).

It could be another mod interfering?  Can you reproduce the problem in an instance with just FTB Quests and minimal other mods?  (REI should be fine)

**Comment by Abalieno** [comment]
It's hard to reproduce already without changing anything. So without some debugging infos it's impossible to test.

For example I rolled back all the quests, and they all completed normally the second time.

**Comment by Matikari** [comment]
I'm getting the same sort of thing with the Create Astral pack. Tho i just discovered if i have the items in inventory and i scroll wheel an item from a chest, the quest will update.

hope this will be a lead to figure out whats conflicting.

**Comment by desht** [comment]
Items are detected on an inventory change, for performance reasons (constantly scanning inv for items is a no-go; it would just lag everyone out). Which explains why the item was correctly detected when you move something else into your inventory; that triggers a change, and a rescan by FTB Quests.

What it doesn't explain is how the item got into your inventory in the first place without triggering an inventory change. If I knew how you acquired the items in question, that might be helpful.

**Comment by Linguardium** [comment]
this issue seems to be significantly more of an issue in single player vs servers. I have not experienced this issue on a server. picking up an item from the ground does not seem to trigger the check. Crafting an item (any item) does seem to trigger the check.  

In previous versions, just moving the item while in the crafting table was enough but in 1.19.2, that doesnt seem to trigger the check anymore and you actually must craft something.

**Comment by desht** [comment]
I'm not seeing this happen in the current version, either in single player or on a server.  So not sure why this is happening to you.

Does setting "Item Auto-Detection Minimum Interval" to 0 in the quest file settings help?

**Comment by Linguardium** [comment]
actually, that is a good catch. I updated the version in the aof6 pack from 1902.4.14-build.223 to 1902.4.17-build.240 and upon load it was able to immediately detect the items in the inventory. (even reloads didnt resolve it previously)  

I would assume that one of the updates between them resolved the underlying issue with detection or the mechanism behind it changed

**Comment by desht** [comment]
Yes, that is the case - it was fixed in 1902.4.15.  See https://github.com/FTBTeam/FTB-Quests/blob/main/CHANGELOG.md for more info.

**Comment by SuperKael** [comment]
Any fix or workaround for the issue in the 1.18 version of the mod? I'm playing Create Astral, which is affected by this issue as was mentioned earlier in this thread.

**Comment by Linguardium** [comment]
1.18 also had inventory detection issues as mentioned that could be worked around by moving items while in a vanilla crafting table

**Comment by 2shabbs** [comment]
I'm having the same problem on a server using ftb-quests-fabric-2001.2.0
The quest is just to make a chest. I've made several, placed several, picked up several, and it still won't detect any. It shows a grey check-mark on the chest, like maybe I can complete, but click on it and it won't detect the chest.
![2024-04-21_10 18 17](https://github.com/FTBTeam/FTB-Mods-Issues/assets/160208268/6ca56a59-072e-4b0c-a6af-ceb0edfcf4fe)

**Comment by desht** [comment]
@2shabbs please create a new issue for this. Your problem is not related to this issue.

**Comment by jasonjay159** [comment]
So your saying I should try every mod one by one and try and see whats happening
